(refactor) chat Function
Auto-merging cbnu_match/moit/chat/models.py
CONFLICT (content): Merge conflict in cbnu_match/moit/chat/models.py
Auto-merging cbnu_match/moit/chat/views.py
CONFLICT (content): Merge conflict in cbnu_match/moit/chat/views.py
error: could not apply 71a9fd5... (refactor) chat Function
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply 71a9fd5... (refactor) chat Functionodified:   cbnu_match/moit/templates/chat/chat.html
Auto-merging cbnu_match/moit/chat/models.py
CONFLICT (content): Merge conflict in cbnu_match/moit/chat/models.py
Auto-merging cbnu_match/moit/chat/views.py
CONFLICT (content): Merge conflict in cbnu_match/moit/chat/views.py
error: could not apply 71a9fd5... (refactor) chat Function
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not applt 71a9fd5... (refactor) chat Function